### ISSUE TITLE
Change Flask default port

### ISSUE THREAD

**Issue by antingle** [FSU-SP2023-SELab/group-1-lottopool#13]
Found out that apparently Mac uses ports 5000 and 7000 locally for Airplay/Control Center. This interferes with running the Flask server on the default port of 5000. Doing an api call to http://localhost:5000/api/hello-world gives a 403 status code. The fix to this is to change the default port. Source for the issue [here](https://stackoverflow.com/questions/72795799/how-to-solve-403-error-with-flask-in-python).

Suggest to change the default port to something like 8000 to avoid interference down the line for the Mac users.

**Comment by Azure-Agst** [comment]
LMFAO That's so freakin dumb. Lord knows why they didn't pick any other port that isn't a common dev port.

Have you tried turning off Airplay Reciever? I think that's the feature bound to that port, and it's a feature so infrequently used, I figured I'd ask. In the meantime just use the `flask run --port 8000` command to get around this.

For now, I'll call this bug non-critical, but I'll also suggest we get a bug patch out sometime after the first iteration. Probably add the option to specify the port in an environment variable, so we can set the value per machine in `.flaskenv`.

**Comment by antingle** [comment]
LOL I know right? You would think they would choose a port that isn't extremely common for dev?

I do not want to turn the feature off because Airplay is something I use occasionally.

Definitely a non-critical bug. I have been starting flask on a different port as of now with that command. I just figured we might as well change the default in case the other group members don't know what is happening if it isn't working. Setting the port in the env sounds like a good idea, since in production we may have a different port.

**Comment by antingle** [comment]
Good to close this issue, if we are agreed to using Doppler as a team. The flask port is being setup over an env variable in Doppler. It is actually important that we use the same port, as the frontend also relies on an env variable to connect to the correct backend url.

**Comment by Azure-Agst** [comment]
Agreed :)
